---
- name: Install dumb init
  get_url: dest=/usr/bin/dumb-init url=https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64 mode=0775 validate_certs=no

- name: Install epel
  yum: name=epel-release state=present 

- name: Install python deps
  yum: name="{{ item }}" state=latest update_cache=yes
  with_items: "{{ DJANGO_RPM_DEPS }}"

- name: Make Django user
  user: name="{{ DJANGO_USER }}" uid=1000 group=root state=present createhome=yes home="{{ DJANGO_ROOT }}"

- name: Make virtualenv dir
  file: name="{{ DJANGO_VENV }}" state=directory owner="{{ DJANGO_USER }}" group=root mode=0775

- name: Make staticfiles dir
  file: name="{{ DJANGO_STATIC_ROOT }}" state=directory owner="{{ DJANGO_USER }}" group=root mode=0775

- name: Setup virtualenv
  command: virtualenv . chdir="{{ DJANGO_VENV }}" creates="{{ DJANGO_VENV }}/bin/python"
  remote_user: "{{ DJANGO_USER }}"

- name: Copy source
  copy: src="{{ lookup('pipe','dirname `pwd`') }}/" dest="{{ DJANGO_ROOT }}" owner="{{ DJANGO_USER }}"
  remote_user: "{{ DJANGO_USER }}"

- name: Install requirements
  pip: executable="{{ DJANGO_VENV }}/bin/pip" requirements="{{ DJANGO_ROOT }}/requirements.txt"
  remote_user: "{{ DJANGO_USER }}"

- name: Collect staticfiles
  command: "{{ DJANGO_VENV }}/bin/python manage.py collectstatic --noinput"
  args:
    chdir: "{{ DJANGO_ROOT }}"
  remote_user: "{{ DJANGO_USER }}"

- name: Itemize Django static assets
  find: paths="{{ DJANGO_STATIC_ROOT }}" recurse=yes
  register: django_assets

- name: Fetch Django static assets
  fetch: src="{{ item.path }}" dest=/tmp
  with_items: "{{ django_assets.files }}"

- name: Change /django permissions
  file:
    path: "{{ DJANGO_ROOT }}"
    state: directory
    owner: django
    group: root
    mode: 0775 

- name: Create startup directory
  file:
    path: /startup
    state: directory
    owner: "{{ DJANGO_USER }}" 
    group: root
    mode: 0775

- name: Copy entrypoint
  copy:
    src: "{{ role_path }}/files/entrypoint.sh" 
    dest: /usr/bin/entrypoint.sh
    owner: root
    group: root
    mode: 0775

- name: Copy startup files
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/startup/{{ item }}"
    owner: "{{ DJANGO_USER }}" 
    group: root
    mode: 0664
  with_items: 
  - inventory
  - migrate.yml
