- hosts: django
  roles:
  - django-gunicorn

- hosts: gulp
  roles:
  - gulp-static

- hosts: nginx
  roles:
  - role: chouseknecht.nginx-container-1
    ASSET_PATHS:
    - /tmp/static
    PROXY_DJANGO: yes
    PROXY_DJANGO_PASS: http://django:8080/
